### ISSUE TITLE
 Cinnamon Multi-Line Taskbar doesn't work in Cinnamon 5.6.5

### ISSUE THREAD

**Issue by afonsky** [linuxmint/cinnamon-spices-applets#4650]
* Build date Nov 17, 2016
 * Cinnamon version 5.6.5
 * Distribution Debian bookworm
 * Graphics hardware *and* driver used: [AMD/ATI] Renoir (rev d9)
 * Snippet of ~/.xsession-errors:
```_init@/home/alexey/.local/share/cinnamon/applets/cinnamon-multi-line-taskbar-applet/applet.js:804:35
MyApplet@/home/alexey/.local/share/cinnamon/applets/cinnamon-multi-line-taskbar-applet/applet.js:733:10
main@/home/alexey/.local/share/cinnamon/applets/cinnamon-multi-line-taskbar-applet/applet.js:1094:20
createApplet@/usr/share/cinnamon/js/ui/appletManager.js:597:25
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:372:34
finishExtensionLoad@/usr/share/cinnamon/js/ui/appletManager.js:98:14
_init/<@/usr/share/cinnamon/js/ui/extension.js:276:32
---------------->
Gjs-Message: 23:41:31.656: JS LOG: [LookingGlass/error] GSettings key window-list-applet-scroll not found in schema org.cinnamon
Gjs-Message: 23:41:31.656: JS LOG: [LookingGlass/trace] 
<----------------
_checkKey@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:575:23
createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:527:30
on_scroll_mode_changed@/home/alexey/.local/share/cinnamon/applets/cinnamon-multi-line-taskbar-applet/applet.js:363:42
_init@/home/alexey/.local/share/cinnamon/applets/cinnamon-multi-line-taskbar-applet/applet.js:355:14
AppMenuButton@/home/alexey/.local/share/cinnamon/applets/cinnamon-multi-line-taskbar-applet/applet.js:242:10
_windowAdded@/home/alexey/.local/share/cinnamon/applets/cinnamon-multi-line-taskbar-applet/applet.js:957:25
on_applet_added_to_panel@/home/alexey/.local/share/cinnamon/applets/cinnamon-multi-line-taskbar-applet/applet.js:847:22
on_applet_added_to_panel_internal@/usr/share/cinnamon/js/ui/applet.js:384:14
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:413:16
finishExtensionLoad@/usr/share/cinnamon/js/ui/appletManager.js:98:14
_init/<@/usr/share/cinnamon/js/ui/extension.js:276:32
---------------->
Gjs-Message: 23:41:31.662: JS LOG: [LookingGlass/error] GSettings key window-list-applet-scroll not found in schema org.cinnamon
Gjs-Message: 23:41:31.662: JS LOG: [LookingGlass/trace] 
<----------------
_checkKey@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:575:23
createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:527:30
on_scroll_mode_changed@/home/alexey/.local/share/cinnamon/applets/cinnamon-multi-line-taskbar-applet/applet.js:363:42
_init@/home/alexey/.local/share/cinnamon/applets/cinnamon-multi-line-taskbar-applet/applet.js:355:14
AppMenuButton@/home/alexey/.local/share/cinnamon/applets/cinnamon-multi-line-taskbar-applet/applet.js:242:10
_windowAdded@/home/alexey/.local/share/cinnamon/applets/cinnamon-multi-line-taskbar-applet/applet.js:957:25
on_applet_added_to_panel@/home/alexey/.local/share/cinnamon/applets/cinnamon-multi-line-taskbar-applet/applet.js:847:22
on_applet_added_to_panel_internal@/usr/share/cinnamon/js/ui/applet.js:384:14
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:413:16
finishExtensionLoad@/usr/share/cinnamon/js/ui/appletManager.js:98:14
_init/<@/usr/share/cinnamon/js/ui/extension.js:276:32
---------------->
Gjs-Message: 23:41:31.667: JS LOG: [LookingGlass/error] GSettings key window-list-applet-scroll not found in schema org.cinnamon
Gjs-Message: 23:41:31.667: JS LOG: [LookingGlass/trace] 
<----------------
_checkKey@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:575:23
createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:527:30
on_scroll_mode_changed@/home/alexey/.local/share/cinnamon/applets/cinnamon-multi-line-taskbar-applet/applet.js:363:42
_init@/home/alexey/.local/share/cinnamon/applets/cinnamon-multi-line-taskbar-applet/applet.js:355:14
AppMenuButton@/home/alexey/.local/share/cinnamon/applets/cinnamon-multi-line-taskbar-applet/applet.js:242:10
_windowAdded@/home/alexey/.local/share/cinnamon/applets/cinnamon-multi-line-taskbar-applet/applet.js:957:25
on_applet_added_to_panel@/home/alexey/.local/share/cinnamon/applets/cinnamon-multi-line-taskbar-applet/applet.js:847:22
on_applet_added_to_panel_internal@/usr/share/cinnamon/js/ui/applet.js:384:14
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:413:16
finishExtensionLoad@/usr/share/cinnamon/js/ui/appletManager.js:98:14
_init/<@/usr/share/cinnamon/js/ui/extension.js:276:32
---------------->
Gjs-Message: 23:41:31.672: JS LOG: [LookingGlass/error] GSettings key window-list-applet-scroll not found in schema org.cinnamon
Gjs-Message: 23:41:31.672: JS LOG: [LookingGlass/trace] 
<----------------
_checkKey@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:575:23
createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:527:30
on_scroll_mode_changed@/home/alexey/.local/share/cinnamon/applets/cinnamon-multi-line-taskbar-applet/applet.js:363:42
_init@/home/alexey/.local/share/cinnamon/applets/cinnamon-multi-line-taskbar-applet/applet.js:355:14
AppMenuButton@/home/alexey/.local/share/cinnamon/applets/cinnamon-multi-line-taskbar-applet/applet.js:242:10
_windowAdded@/home/alexey/.local/share/cinnamon/applets/cinnamon-multi-line-taskbar-applet/applet.js:957:25
on_applet_added_to_panel@/home/alexey/.local/share/cinnamon/applets/cinnamon-multi-line-taskbar-applet/applet.js:847:22
on_applet_added_to_panel_internal@/usr/share/cinnamon/js/ui/applet.js:384:14
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:413:16
finishExtensionLoad@/usr/share/cinnamon/js/ui/appletManager.js:98:14
_init/<@/usr/share/cinnamon/js/ui/extension.js:276:32
---------------->
Gjs-Message: 23:41:31.677: JS LOG: [LookingGlass/error] GSettings key window-list-applet-scroll not found in schema org.cinnamon
Gjs-Message: 23:41:31.677: JS LOG: [LookingGlass/trace] 
<----------------
_checkKey@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:575:23
createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:527:30
on_scroll_mode_changed@/home/alexey/.local/share/cinnamon/applets/cinnamon-multi-line-taskbar-applet/applet.js:363:42
_init@/home/alexey/.local/share/cinnamon/applets/cinnamon-multi-line-taskbar-applet/applet.js:355:14
AppMenuButton@/home/alexey/.local/share/cinnamon/applets/cinnamon-multi-line-taskbar-applet/applet.js:242:10
_windowAdded@/home/alexey/.local/share/cinnamon/applets/cinnamon-multi-line-taskbar-applet/applet.js:957:25
on_applet_added_to_panel@/home/alexey/.local/share/cinnamon/applets/cinnamon-multi-line-taskbar-applet/applet.js:847:22
on_applet_added_to_panel_internal@/usr/share/cinnamon/js/ui/applet.js:384:14
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:413:16
finishExtensionLoad@/usr/share/cinnamon/js/ui/appletManager.js:98:14
_init/<@/usr/share/cinnamon/js/ui/extension.js:276:32
---------------->
Gjs-Message: 23:41:31.678: JS LOG: [LookingGlass/info] Loaded applet cinnamon-multi-line-taskbar-applet in 72 ms

(cinnamon:2001): Gjs-CRITICAL **: 23:41:31.763: JS ERROR: TypeError: this._animations.hide_all is not a function
_update@/usr/share/cinnamon/js/ui/panel.js:1336:26


(cinnamon:2001): Gjs-CRITICAL **: 23:41:31.763: JS ERROR: TypeError: this._animations.hide_all is not a function
_update@/usr/share/cinnamon/js/ui/panel.js:1336:26


(cinnamon:2001): Gjs-CRITICAL **: 23:41:31.763: JS ERROR: TypeError: this._animations.hide_all is not a function
_update@/usr/share/cinnamon/js/ui/panel.js:1336:26


(cinnamon:2001): Gjs-CRITICAL **: 23:41:31.768: JS ERROR: TypeError: this._animations.hide_all is not a function
_update@/usr/share/cinnamon/js/ui/panel.js:1336:26


(cinnamon:2001): Gjs-CRITICAL **: 23:41:31.778: JS ERROR: TypeError: this._animations.hide_all is not a function
_update@/usr/share/cinnamon/js/ui/panel.js:1336:26
```

**Issue**
After upgrading Debian from bullseye to bookworm and  Cinnamon 4.8.6 to Cinnamon 5.6.5 the applet stopped working. Step 5 from the applet's installation doesn't enable applet and produces errors in ~/.xsession-errors provided above.

**Steps to reproduce**
1. Download the applet and install to ~/.local/share/cinnamon/applets/
2. Go to Menu > Cinnamon Settings > Applets
3. Ensure applet 'Cinnamon Multi-Line taskbar' is present
4. Uncheck the default 'Cinnamon Window List'
5. Enable applet 'Cinnamon Multi-Line taskbar'

**Other information**
The applet worked in Cinnamon 4.8.6 and Debian bullseye.

**Comment by Drugwash2** [comment]
Would you kindly attempt to install the **[mod](https://github.com/Drugwash2/multi-line-taskbar)** I've been working on, see if it works for you? If you do please mind its ID has been changed together with the name.

For the moment I no longer have the working Mint 21 installation to check whether it's still working in latest Cinnamon, and no other recent Cinnamon system either, so hopefully it works as is.

**Comment by afonsky** [comment]
@Drugwash2: Thank you very much for your mod and for the answer!

Unfortunately, it doesn't work with this version either. The mod just doesn't start. I only see the tick and clickable gears button ('Configure') in the applets menu. But after clicking on that button nothing happens. I also don't see any errors in the .xsession-errors from the modified version of the applet.

**Comment by Drugwash2** [comment]
Ah, sorry to hear that. Lack of error log makes it even harder to pinpoint the issue.
My test machine just broke down and got no replacement so can't perform any tests myself. Hopefully someone else could offer a hand.

By the way, the error in the original log related to `this._animations.hide_all` pertains to the Cinnamon file **panel.js** that has not been updated as the function `hide_all()` has been deprecated and should be replaced with `hide()`.

**Comment by afonsky** [comment]
I just double-checked that both the applet and the mod are faulty on a freshly installed Debian bookworm and Cinnamon 5.6.5 in a virtual machine.

**Comment by Drugwash2** [comment]
Would you by chance be able to check with a different Cinnamon distro too? So far I only tested in Mint 19.2 and Mint 21 beta but not in Mint 21.1. There may be slight differences in the distros that could make the applet not work. I can't get a VM up and running very soon, if ever (poor people and old/bad/missing hardware are a sorry mix).

**Comment by afonsky** [comment]
On the Mint 21.1 and Cinnamon 5.6.5, vanilla and modded applets do not work either.

**Comment by Drugwash2** [comment]
OK, there must be some major change under the hood in this newer 5.6 Cinnamon, it used to work in 5.4. Could it be on purpose?
Will see if I can crop up a suitable VM one of these days.
Thank you very much for testing. 👍

**Comment by Drugwash2** [comment]
Earlier today I managed to install Mint 21.1 Cinnamon in VirtualBox, updated to Cinnamon 5.6.7 and tested all my applets including the multi-line mod. All applets loaded and worked correctly save for a couple minor issues (not in the multi-line mod).
At this point I really don't know what to say. Maybe try to select the Traditional panel type in the Welcome Screen, see if that helps?
If you do that please be aware all panel settings and enabled applets will be wiped out.

![Screenshot from 2023-01-21 22-57-29](https://user-images.githubusercontent.com/29117024/213886956-f0ed4b27-7e5f-4958-aa27-d9108d023d3a.png)

**Comment by afonsky** [comment]
Hi @Drugwash2,

It is very strange that we have different behaviour of the applet while using the same packages inside a VM.

I updated Cinnamon to 5.6.7 and still can't start the applet. I also tried to select the Traditional panel type as you advised.

Using Melange Debugger I realized that vanilla Multi-Line Taskbar loaded with errors but doesn't work (nothing happened in the panel):
![VirtualBox_MintTest_22_01_2023_21_39_53](https://user-images.githubusercontent.com/30157711/213934349-362dfce5-2984-45fc-af8e-a439fc37fc2b.png)

But modded applet even doesn't started - it isn't appeared in any place in the Melange.

Anyway, thanks for your help.

**Comment by Drugwash2** [comment]
The official applet has issues that might never get fixed, certain functions that have been deprecated recently or some time ago. It had issues even on Mint 19.2 which is my daily driver. That's why I took on modding it.

Now, for me it works fine - with minor quirks that I might attempt to fix at some point - in Mint 19.2. After struggling with installing,  updating and minor tweaking Mint 21.1 in VM over a mapped networked drive it worked right away. I even had to download and install the very packages (zip archives) from my own GitHub repository because the VBox setup in present configuration doesn't allow shared folders, so that's a sure test that the public code is OK.

Did you install the zip package or downloaded the code files? The folder name for this particular applet mod should be **multilineWL@drugwash** otherwise it won't work. Please double-check. There should be no other reason why it shouldn't work for you - at least in Mint 21.1.

**Comment by claudiux** [comment]
`No signal 'maximize' on object 'CinnamonWM'`

**Comment by Drugwash2** [comment]
@claudiux That one is fixed in my mod together with some others. Have you tried it...?

**Comment by Drugwash2** [comment]
Yeah, this git stuff is messed up. For some reason it's completely opposite to my line of thinking so no wonder things come out wrong at times. Sorry about that.
I modified the readme file adding a notification about the correct folder name.
Also fixed a small issue with the spinner animation (still not perfect though).
No release package though.
