### ISSUE TITLE
sysmonitor@orcus: GTop.glibtop.get_netlist is not a function

### ISSUE THREAD

**Issue by sruggier** [linuxmint/cinnamon-spices-applets#1008]
```
Window manager warning: Log level 16: Symbolic icon /usr/share/icons/hicolor/scalable/actions/pan-end-symbolic.svg of size 16 is in an icon theme directory of size 128

(cinnamon:3754): Cjs-WARNING **: JS ERROR: Exception in method call: updateSetting: TypeError: GTop.glibtop.get_netlist is not a function
NetData.prototype._init@/home/sruggier/.local/share/cinnamon/applets/sysmonitor@orcus/providers.js:111
NetData@/home/sruggier/.local/share/cinnamon/applets/sysmonitor@orcus/providers.js:104
MyApplet.prototype.on_cfg_changed_graph_enabled/enable@/home/sruggier/.local/share/cinnamon/applets/sysmonitor@orcus/applet.js:265
MyApplet.prototype.on_cfg_changed_graph_enabled@/home/sruggier/.local/share/cinnamon/applets/sysmonitor@orcus/applet.js:280
bind/<@resource:///org/gnome/gjs/modules/lang.js:95
XletSettingsBase.prototype._checkSettings@/usr/share/cinnamon/js/ui/settings.js:570
XletSettingsBase.prototype.remoteUpdate@/usr/share/cinnamon/js/ui/settings.js:746
CinnamonDBus.prototype.updateSetting@/usr/share/cinnamon/js/ui/cinnamonDBus.js:333
_handleMethodCall@resource:///org/gnome/gjs/modules/overrides/Gio.js:261
_wrapJSObject/<@resource:///org/gnome/gjs/modules/overrides/Gio.js:331
```

This started happening when I upgraded cinnamon to 3.4, and then updated the applet, because the previous version I had was a couple of years old and wouldn't start following the Cinnamon upgrade.

@OrcusCZ 

 - Distribution (In a terminal run "lsb_release -a".)

    No LSB modules are available.
    Distributor ID:	LinuxMint
    Description:	LMDE 2 Betsy
    Release:	2
    Codename:	betsy

 - Cinnamon version (In a terminal run "cinnamon --version".)

    Cinnamon 3.4.4

 - Applet version (Right-click the applet, then click "About...", or go to its directory and include the version/last-edited values in metadata.json.)

    2017-06-30 20:15:06 UTC

 - ~/.cinnamon/glass.log (Use pastebin or a small snippet that's relavent to the issue.)
 - ~/.xsession-errors

The error above was from .xsession-errors.

**Comment by OrcusCZ** [comment]
I've installed LMDE 2 Betsy in VM and was able to reproduce the issue.
For some reason, get_netlist function is not exported through GObject introspection (its gir file contains "introspectable=0"), although netlist structure is, but it can't be used for anything without that function. I am not sure where this problem comes from and if something can be done about it, since I don't understand GObject introspection that well.

Older versions of this applet used network manager to retrieve a list of network interfaces. Not everyone uses network manager, so I dropped this dependency in favor of glibtop's netlist feature. I can add fallback to either network manager or use directly /sys/class/net to retrieve the interfaces. I think the latter is better, because it doesn't create any additional dependency.

I've modified the applet to use /sys/class/net if netlist fails, could you replace providers.js with this file and test if it works for you?
https://github.com/OrcusCZ/cinnamon-spices-applets/blob/sysmon-netlist/sysmonitor%40orcus/files/sysmonitor%40orcus/providers.js

**Comment by sruggier** [comment]
Oops, I forgot to follow up on this until now. I downloaded your updated version, diffed it against mine, replaced it, and re-added the applet. After I re-enabled it, the network graph reappeared, so I guess the fallback you implemented is working ;)

**Comment by OrcusCZ** [comment]
Hi, thanks for letting me know it works now. I am glad to hear that :) I will create pull request with my patch so the fix should be live soon.
