### ISSUE TITLE
multi-core-sysmonitor 1.7.2 not working under Mint 18.3

### ISSUE THREAD

**Issue by christian-siewert** [linuxmint/cinnamon-spices-applets#1505]
Strangely enough, since I upgraded from Mint 18.2 to 18.3, the _multicore-sys-monitor_ applet doesn't work anymore. I can still add the applet to the bar, but it is not visible. In addition, the settings can no longer be called up. Does it still take some time until the applet works correctly on 18.3?

Best,
Christian

**Comment by jaszhix** [comment]
Please pastebin ~/.xsession_errors.

**Comment by NikoKrause** [comment]
Post a screenshot of the about dialog

**Comment by christian-siewert** [comment]
Strange. It suddenly works. The version hasn't changed, but I had to restart Cinnamon due to a freeze of the user interface. Thanks for the help anyway.
![image](https://user-images.githubusercontent.com/33094503/33319777-1df1d838-d440-11e7-8bf1-2021dc5014f4.png)

**Comment by christian-siewert** [comment]
@jaszhix 

https://gist.github.com/anonymous/feddb9e0a93889532d1b2d2ccd74da5f

**Comment by jaszhix** [comment]
Thanks. Yes, looks like a problem with the applet.

```
(cinnamon:2784): Cjs-WARNING **: JS ERROR: TypeError: this.configSettings.isCPUEnabled is not a function
MyApplet.prototype.getAppletWidth@/home/christian/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/3.4/applet.js:223:9
MyApplet.prototype.__init@/home/christian/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/3.4/applet.js:93:28
MyApplet.prototype._init/<@/home/christian/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/3.4/applet.js:77:9
spawnCommandLineAsync/<@/usr/share/cinnamon/js/misc/util.js:178:17

Cinnamon warning: Log level 8: cinnamon_tray_manager_manage_stage: assertion 'manager->priv->stage == NULL' failed

(cinnamon:2784): Cjs-WARNING **: JS ERROR: TypeError: this.configSettings.isCPUEnabled is not a function
MyApplet.prototype.getAppletWidth@/home/christian/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/3.4/applet.js:223:9
MyApplet.prototype.__init@/home/christian/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/3.4/applet.js:93:28
MyApplet.prototype._init/<@/home/christian/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/3.4/applet.js:77:9
spawnCommandLineAsync/<@/usr/share/cinnamon/js/misc/util.js:178:17
```

Not sure what else is going on in the log though  - seeing a lot of errors all over the place, but the applet should be able to handle itself in any environment.

**Comment by jaszhix** [comment]
Actually, the line numbers aren't matching up. Something weird happened, and not sure why it says the version is 1.7.2. May be an incomplete upgrade. 

Remove the applet completely.

`rm -rf ~/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23`

Then go into Applet Settings, click the Download tab, click the refresh icon on the bottom right. Then see if there's an update.

**Comment by christian-siewert** [comment]
Well... nothing's changed. Version is still 1.7.2 and the applet works. Everything's all right. Who knows what it was exactly. Maybe it went together with the upgrade to Mint 18.3.
