### ISSUE TITLE
clipboard-qr@wrouesnel doesn't work with LM 18.3

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/cinnamon-spices-applets#1590]
clipboard-qr@wrouesnel

 * Applet version 1.12
 * Cinnamon 3.6.7
 * LM 18.3
 * Graphics hardware *and* driver used
inxi -Gx
Graphics:  Card-1: Intel 3rd Gen Core processor Graphics Controller
           bus-ID: 00:02.0
           Card-2: Advanced Micro Devices [AMD/ATI] Venus XT [Radeon HD 8870M / R9 M270X/M370X]
           bus-ID: 01:00.0
           Display Server: X.Org 1.18.4 drivers: ati,radeon,intel (unloaded: fbdev,vesa)
           Resolution: 1920x1080@60.21hz
           GLX Renderer: Mesa DRI Intel Ivybridge Mobile
           GLX Version: 3.0 Mesa 17.2.4 Direct Rendering: Yes

 * Snippet or attachment of ~/.xsession-errors
(cinnamon:2377): Cjs-WARNING **: JS ERROR: Error: Too few arguments to method St.Clipboard.get_text: expected 2, got 1
MyApplet.prototype.on_applet_clicked@/home/user1/.local/share/cinnamon/applets/clipboard-qr@wrouesnel/applet.js:149:1
Applet.prototype._onButtonPressEvent@/usr/share/cinnamon/js/ui/applet.js:284:21

@wrouesnel
clipboard-qr opens no menu when left clicked; used to work previously.
python-zbar is installed.

**Comment by alex-t-grecu** [comment]
If maintainer would like to patch this nice applet the solution is simple. According to Cinnamon 3.6.7 changelog (https://github.com/linuxmint/Cinnamon/blob/master/debian/changelog) the function signature was changed for St.Clipboard.get_text to support different types of clipboard. A simple patch is needed on the indicated line in applet.js to add St.ClipboardType.CLIPBOARD as first argument of clipboard.get_text in on_applet_clicked event sink. This will of course break compatibility to previous cinnamon versions so I'm looking forward to a smarter implementation from the main developer.

**Comment by Mintulix** [comment]
@alex-t-grecu Thanks for your solution, left click works again. But "Scan QR-Code with WebCam" still doesn't work. Do you have another clue?

**Comment by Mintulix** [comment]
@alex-t-grecu Sorry, my fault. clipboard-qr.py had no right to be executed. Works now. Thanks a lot and let's wait for a global solution from @wrouesnel

**Comment by alex-t-grecu** [comment]
Glad to be of some help. Maybe you could contribute to increasing the score of the applet (https://cinnamon-spices.linuxmint.com/applets/view/213) and further motivate the maintainer. I guess it was mentioned somewhere in the code that the applet is just a side project so maybe that is why the general solution implementation will take some time. And of course the GJS/CJS documentation is very unreliable to say the least which is also a pity...

**Comment by new-on-github** [comment]
Same problem here:

Can someone help me with the by @alex-t-grecu suggested solution? I have to change the applet.js file? Where can i find this file?

It would be nice if someone can help me.

**Comment by NikoKrause** [comment]
I implemented the fix suggested by @alex-t-grecu. Thanks.

@new-on-github 
You just need to update the applet and then to restart Cinnamon.
